version: '3.8'

services:

  app_module:
    build: ./api
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/usr/src/api
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - prometheus    

  prometheus:
    image: prom/prometheus
    ports: 
      - 9090:9090
    expose:
      - 9090
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
      - $PWD/prometheus_data:/prometheus